# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLpao74FISI3oXmZi8kI0Nj9fpylfel2

Solution of CIS125 Assignment 1
SID: s22212852
Name: Cheung Siu Chun
"""

# importing useful functions
from math import log2
from collections import Counter

def calculate_entropy(message):
  freq_dict = Counter(message)
  M = len(message)
  H = sum(f/M * log2(M/f) for f in freq_dict.values())
  return H

# Testing with Class Examples
message = "aaaaaaaabbbbccde"
print(f"The message {message} has an entropy of {calculate_entropy(message)}")

message = "aabb"
print(f"The message {message} has an entropy of {calculate_entropy(message)}")

message = "abbb"
print(f"The message {message} has an entropy of {calculate_entropy(message)}")

message = "aabbaacc"
print(f"The message {message} has an entropy of {calculate_entropy(message)}")

message = "I have an apple."
print(f"The message {message} has an entropy of {calculate_entropy(message)}")